---

- name: install aws instances
  hosts: localhost
  connection: local
  vars:
     - ec2_key: "AKIAID3WAKAASRTYT4CA"
     - ec2_secret_key: "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"
     - ec2_keypair_name: "omeraws"
     - image: "ami-194cdc76" # RHEL 7.4
     - vpc_subnet_id: "subnet-86b8dced"
     - group_id: 'sg-61020f0b' # Devops Project Security Group
     - ssh_user: "ec2-user"
     - region: "eu-central-1" # Frankfurt
     - instance_type: "t2.micro" # Free Tier    - /home/ec2-user/Devops_project/vars.yml
  tasks:
    - name: provision
      ec2:
          key_name: "{{ ec2_keypair_name }}"
          access_key: "{{ ec2_key }}"
          secret_key: "{{ ec2_secret_key }}"
          group_id: "{{ group_id }}"
          region: "{{ region }}"
          instance_type: "{{instance_type}}"
          image: "{{image}}"
          vpc_subnet_id: "{{ vpc_subnet_id}}"
          wait: true
          volumes:
            - device_name: /dev/sda1
              volume_size: 10
              delete_on_termination: true
              instance_tags:
                Name: ["Jenkins Server", "Build Node", "Target Node"]
          count: 3



